/*
CircuitSimulator.java
Single-file Java Swing application for IntelliJ that draws a simple electronic-circuit-like diagram
(similar style to Logisim) and records power ON/OFF timestamps to an Oracle 19c database.

INSTRUCCIONES RÁPIDAS:
1) Añade el driver Oracle (ojdbc11.jar o la versión compatible) al classpath / Module Dependencies en IntelliJ.
2) Ajusta las constantes DB_URL, DB_USER, DB_PASSWORD en la clase OracleDAO con tus credenciales y host.
3) Ejecuta this file como aplicación Java (Run -> Run 'CircuitSimulator').
4) Crea la tabla en Oracle antes de ejecutar (ejemplo SQL abajo).

SQL para crear la tabla (ejemplo):

CREATE TABLE CIRCUIT_LOG (
  ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  STATE VARCHAR2(10) NOT NULL,
  EVENT_TIME TIMESTAMP DEFAULT SYSTIMESTAMP
);

Descripción del comportamiento:
- Ventana con dibujo simple de un circuito (fuente, conmutador, LED) realizado con Java2D.
- Botón "Power" que alterna el estado: ON / OFF.
- Cada cambio de estado inserta un registro en Oracle con el estado y la marca de tiempo.
- Visualización del último evento en la interfaz.

Nota de seguridad: Mantén las credenciales de la BD fuera del código en producción (usa variables de entorno o un vault).
*/

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.awt.geom.Ellipse2D;
import java.sql.*;
import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;


public class CircuitSimulator extends JFrame {
    public static void main(String[] args) {
        //TIP Press <shortcut actionId="ShowIntentionActions"/> with your caret at the highlighted text
        // to see how IntelliJ IDEA suggests fixing it.
        System.out.printf("Hello and welcome!");

        for (int i = 1; i <= 5; i++) {
            //TIP Press <shortcut actionId="Debug"/> to start debugging your code. We have set one <icon src="AllIcons.Debugger.Db_set_breakpoint"/> breakpoint
            // for you, but you can always add more by pressing <shortcut actionId="ToggleLineBreakpoint"/>.
            System.out.println("i = " + i);
        }
    }
}